//! The contract: every vector generated by the Python reference
//! (scripts/golden_vectors.py -> node/vectors/golden.json) must reproduce
//! bit-exactly. If this fails, the Rust node is wrong — the rig is the spec.

use sestrian_core as core;
use serde_json::Value;

fn vectors() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../vectors/golden.json");
    serde_json::from_str(&std::fs::read_to_string(path).expect("golden.json missing"))
        .expect("golden.json invalid")
}

fn f64s(v: &Value) -> Vec<f64> {
    v.as_array().unwrap().iter().map(|x| x.as_f64().unwrap()).collect()
}
fn i64s(v: &Value) -> Vec<i64> {
    v.as_array().unwrap().iter().map(|x| x.as_i64().unwrap()).collect()
}

#[test]
fn quantize_matches_reference() {
    for case in vectors()["quantize"].as_array().unwrap() {
        assert_eq!(core::quantize(&f64s(&case["f"])), i64s(&case["q"]),
                   "quantize mismatch (round-half-to-even?)");
    }
}

#[test]
fn state_root_matches_reference() {
    for case in vectors()["state_root"].as_array().unwrap() {
        assert_eq!(core::state_root(&i64s(&case["w"])),
                   case["root"].as_str().unwrap(),
                   "state_root mismatch (endianness?)");
    }
}

#[test]
fn trimmed_mean_matches_reference() {
    for case in vectors()["trimmed_mean"].as_array().unwrap() {
        let deltas: Vec<Vec<i64>> = case["deltas"].as_array().unwrap()
            .iter().map(i64s).collect();
        assert_eq!(core::trimmed_mean(&deltas, 0.2), i64s(&case["mean"]),
                   "trimmed_mean mismatch (floor division?)");
    }
}

#[test]
fn delta_hash_matches_reference() {
    for case in vectors()["delta_hash"].as_array().unwrap() {
        let d = i64s(&case["delta"]);
        assert_eq!(core::delta_hash(&core::int64_bytes(&d)),
                   case["hash"].as_str().unwrap());
    }
}

#[test]
fn decompress_matches_reference() {
    for case in vectors()["decompress"].as_array().unwrap() {
        let idx = hex::decode(case["idx_hex"].as_str().unwrap()).unwrap();
        let val = hex::decode(case["val_hex"].as_str().unwrap()).unwrap();
        let n = case["n"].as_u64().unwrap() as usize;
        assert_eq!(core::decompress(n, &idx, &val), i64s(&case["dense"]));
    }
}

#[test]
fn ed25519_matches_reference() {
    for case in vectors()["ed25519"].as_array().unwrap() {
        let seed: [u8; 32] = hex::decode(case["seed_hex"].as_str().unwrap())
            .unwrap().try_into().unwrap();
        let key = core::Key::from_seed(seed);
        assert_eq!(key.pub_hex(), case["pub_hex"].as_str().unwrap(),
                   "pubkey derivation mismatch");
        let msg = hex::decode(case["msg_hex"].as_str().unwrap()).unwrap();
        assert_eq!(hex::encode(key.sign(&msg)), case["sig_hex"].as_str().unwrap(),
                   "signature mismatch (RFC 8032 is deterministic)");
        assert!(core::verify_sig(&key.pub_hex(), &msg,
                                 &hex::decode(case["sig_hex"].as_str().unwrap()).unwrap()));
    }
}

fn tx_from(t: &Value) -> core::BackpropTx {
    core::BackpropTx {
        miner: t["miner"].as_str().unwrap().into(),
        base_height: t["base_height"].as_u64().unwrap(),
        delta_hash: t["delta_hash"].as_str().unwrap().into(),
        da_pointer: t["da_pointer"].as_str().unwrap().into(),
        bond: t["bond"].as_u64().unwrap_or(0),
        pages: t["pages"].as_array().unwrap()
            .iter().map(|x| x.as_u64().unwrap() as u32).collect(),
        data_refs: t.get("data_refs").and_then(|v| v.as_array())
            .map(|a| a.iter().filter_map(|x| x.as_str().map(String::from)).collect())
            .unwrap_or_default(),
        sig: hex::decode(t["sig_hex"].as_str().unwrap()).unwrap(),
    }
}

#[test]
fn backprop_tx_matches_reference() {
    // v1: shard_id is gone; the signed PAGE CLAIM SET is count-prefixed in the
    // preimage between bond and data_refs.
    for case in vectors()["backprop_tx"].as_array().unwrap() {
        let tx = tx_from(case);
        assert_eq!(hex::encode(tx.signing_bytes()),
                   case["signing_bytes_hex"].as_str().unwrap());
        assert_eq!(tx.txid(), case["txid"].as_str().unwrap());
        assert!(tx.verify(), "tx signature must verify");
    }
}

#[test]
fn txset_root_matches_reference() {
    for case in vectors()["txset_root"].as_array().unwrap() {
        let ids: Vec<String> = case["txids"].as_array().unwrap()
            .iter().map(|x| x.as_str().unwrap().to_string()).collect();
        assert_eq!(core::txset_root(&ids), case["root"].as_str().unwrap());
    }
}

fn header_from(case: &Value) -> core::Header {
    core::Header {
        height: case["height"].as_u64().unwrap(),
        prev_hash: case["prev_hash"].as_str().unwrap().into(),
        state_root: case["state_root"].as_str().unwrap().into(),
        txset_root: case["txset_root"].as_str().unwrap().into(),
        n_txs: case["n_txs"].as_u64().unwrap(),
        work: case["work"].as_u64().unwrap(),
        proposer: case["proposer"].as_str().unwrap().into(),
        transfer_root: case["transfer_root"].as_str().unwrap_or("").into(),
        ledger_root: case["ledger_root"].as_str().unwrap_or("").into(),
        data_root: case["data_root"].as_str().unwrap_or("").into(),
        vrf_proof: case["vrf_proof"].as_str().unwrap_or("").into(),
        score_root: case["score_root"].as_str().unwrap_or("").into(),
        sketch_root: case["sketch_root"].as_str().unwrap_or("").into(),
        model_root: case["model_root"].as_str().unwrap_or("").into(),
        vrf_attempt: case["vrf_attempt"].as_u64().unwrap_or(0),
        version: case["version"].as_u64().unwrap_or(1),
    }
}

#[test]
fn header_hash_matches_reference() {
    for case in vectors()["header"].as_array().unwrap() {
        let h = header_from(case);
        assert_eq!(h.canonical_json(), case["canonical_json"].as_str().unwrap(),
                   "canonical JSON must match python json.dumps(sort_keys=True)");
        assert_eq!(h.block_hash(), case["hash"].as_str().unwrap());
    }
}

#[test]
fn address_and_emission_match_reference() {
    use sestrian_core::token;
    for case in vectors()["address"].as_array().unwrap() {
        assert_eq!(token::address(case["pub_hex"].as_str().unwrap()),
                   case["address"].as_str().unwrap());
    }
    for case in vectors()["emission"].as_array().unwrap() {
        assert_eq!(token::emission(case["height"].as_u64().unwrap()),
                   case["reward"].as_u64().unwrap(),
                   "emission schedule mismatch at height {}", case["height"]);
    }
}

fn transfer_from(t: &Value) -> sestrian_core::token::TransferTx {
    sestrian_core::token::TransferTx {
        from_pub: t["from_pub"].as_str().unwrap().into(),
        to_addr: t["to_addr"].as_str().unwrap().into(),
        amount: t["amount"].as_u64().unwrap(),
        nonce: t["nonce"].as_u64().unwrap(),
        sig: hex::decode(t["sig_hex"].as_str().unwrap()).unwrap(),
    }
}

#[test]
fn ledger_matches_reference() {
    use sestrian_core::token::{self, AccountTx, TokenLedger};
    for case in vectors()["ledger"].as_array().unwrap() {
        let miners: Vec<String> = case["miners"].as_array().unwrap()
            .iter().map(|x| x.as_str().unwrap().to_string()).collect();
        let data: Vec<String> = case["data_addrs"].as_array().unwrap()
            .iter().map(|x| x.as_str().unwrap().to_string()).collect();
        let mut led = TokenLedger::new();
        led.apply_reward(case["height"].as_u64().unwrap(), &miners,
                         case["proposer"].as_str().unwrap(), &data, &Default::default(),
                         &Default::default());
        assert_eq!(led.root(), case["root_after_reward"].as_str().unwrap(),
                   "reward split / ledger-root serialization mismatch");
        let tx = transfer_from(&case["transfer"]);
        assert_eq!(hex::encode(tx.signing_bytes()),
                   case["transfer"]["signing_bytes_hex"].as_str().unwrap());
        assert_eq!(AccountTx::Transfer(tx.clone()).txid(),
                   case["transfer"]["txid"].as_str().unwrap());
        assert!(led.apply_transfer(&tx), "reference transfer must apply");
        assert_eq!(led.root(), case["root_after_transfer"].as_str().unwrap());
        assert_eq!(token::transfer_root(&[tx]),
                   case["transfer_root"].as_str().unwrap());
        for (addr, bal) in case["balances"].as_object().unwrap() {
            assert_eq!(led.balance(addr), bal.as_u64().unwrap());
        }
    }
}

#[test]
fn data_provenance_matches_reference() {
    use sestrian_core::token::TokenLedger;
    use std::collections::BTreeMap;
    for case in vectors()["data_provenance"].as_array().unwrap() {
        let mut led = TokenLedger::new();
        let corpora = case["corpora"].as_object().unwrap();
        for (h, owner) in corpora {
            led.registry.insert(h.clone(), serde_json::json!({
                "owner": owner.as_str().unwrap(), "data_hash": h,
                "size": 0, "media_type": "text", "stake": 0,
                "weight": 1, "status": "active"}));
        }
        let credits: BTreeMap<String, u64> = case["data_credits"].as_object().unwrap()
            .iter().map(|(k, v)| (k.clone(), v.as_u64().unwrap())).collect();
        let miner = case["miner"].as_str().unwrap();
        led.apply_reward(case["height"].as_u64().unwrap(), &[miner.to_string()],
                         miner, &[], &credits, &Default::default());
        // only the NAMED corpus (A) is paid; the unnamed active corpus (B) earns 0
        assert_eq!(led.balance(case["owner_a"].as_str().unwrap()),
                   case["balance_a"].as_u64().unwrap(), "named corpus owner payout");
        assert_eq!(led.balance(case["owner_b"].as_str().unwrap()),
                   case["balance_b"].as_u64().unwrap(), "unnamed corpus must earn 0");
        assert_eq!(led.balance(&sestrian_core::token::address(miner)),
                   case["miner_after"].as_u64().unwrap(), "miner share");
        assert_eq!(led.root(), case["root"].as_str().unwrap(),
                   "provenance-payout ledger root mismatch");
    }
}

#[test]
fn scoring_matches_reference() {
    // rev 7: the miner pool splits ∝ committed delta scores; all-zero weights
    // fall back to the equal split. Roots lock the serialization.
    use sestrian_core::token::{address, TokenLedger};
    use std::collections::BTreeMap;
    for case in vectors()["scoring"].as_array().unwrap() {
        let a = case["miner_a"].as_str().unwrap();
        let b = case["miner_b"].as_str().unwrap();
        let h = case["height"].as_u64().unwrap();
        let weights: BTreeMap<String, u64> = case["weights"].as_object().unwrap()
            .iter().map(|(k, v)| (k.clone(), v.as_u64().unwrap())).collect();
        let mut led = TokenLedger::new();
        led.apply_reward(h, &[a.to_string(), b.to_string()], "genesis", &[],
                         &Default::default(), &weights);
        assert_eq!(led.balance(&address(a)), case["balance_a"].as_u64().unwrap(),
                   "3x-scored miner share");
        assert_eq!(led.balance(&address(b)), case["balance_b"].as_u64().unwrap(),
                   "1x-scored miner share");
        assert_eq!(led.root(), case["root"].as_str().unwrap());
        let mut led_z = TokenLedger::new();
        led_z.apply_reward(h, &[a.to_string(), b.to_string()], "genesis", &[],
                           &Default::default(), &Default::default());
        assert_eq!(led_z.balance(&address(a)), case["equal_balance_a"].as_u64().unwrap());
        assert_eq!(led_z.balance(&address(b)), case["equal_balance_b"].as_u64().unwrap());
        assert_eq!(led_z.root(), case["equal_root"].as_str().unwrap());
    }
}

#[test]
fn fee_flows_match_reference() {
    // rev 6: an inference fee splits 60/20/20 (server instant, data + training
    // slices into the ledger fee pools), and the NEXT block's reward drains the
    // pools to its delta miners + provenance-named data owners.
    use sestrian_core::token::{address, AccountTx, InferenceReceiptTx, TokenLedger};
    use std::collections::{BTreeMap, HashSet};
    for case in vectors()["fee_flows"].as_array().unwrap() {
        let payer = case["payer_pub"].as_str().unwrap();
        let mut led = TokenLedger::new();
        led.apply_reward(1, &[payer.to_string()], "genesis", &[], &Default::default(), &Default::default());
        let rcpt = AccountTx::InferenceReceipt(InferenceReceiptTx {
            payer_pub: payer.into(),
            server_addr: case["server_addr"].as_str().unwrap().into(),
            fee: case["fee"].as_u64().unwrap(),
            output_hash: case["output_hash"].as_str().unwrap().into(),
            head_root: case["head_root"].as_str().unwrap().into(),
            nonce: case["nonce"].as_u64().unwrap(),
            answer_sketch: vec![],
            sig: hex::decode(case["sig_hex"].as_str().unwrap()).unwrap(),
        });
        assert!(led.apply_data_tx(&rcpt, 1, &HashSet::new()), "receipt must apply");
        let s = &case["after_receipt"];
        assert_eq!(led.balance(case["server_addr"].as_str().unwrap()),
                   s["server_after"].as_u64().unwrap(), "server paid 60% + dust");
        assert_eq!(led.fee_data_pool, s["fee_data_pool"].as_u64().unwrap());
        assert_eq!(led.fee_train_pool, s["fee_train_pool"].as_u64().unwrap());
        assert_eq!(led.root(), s["root"].as_str().unwrap(), "post-receipt root");
        // register the corpus, then the next block drains both pools
        led.registry.insert("corpusF".into(), serde_json::json!({
            "owner": case["owner_f"].as_str().unwrap(), "data_hash": "corpusF",
            "size": 0, "media_type": "text", "stake": 0,
            "weight": 1, "status": "active"}));
        let credits: BTreeMap<String, u64> = [("corpusF".to_string(), 1u64)].into();
        let miner = case["miner"].as_str().unwrap();
        led.apply_reward(2, &[miner.to_string()], "genesis", &[], &credits, &Default::default());
        let d = &case["after_drain"];
        assert_eq!(led.balance(&address(miner)),
                   d["miner_after"].as_u64().unwrap(), "miner share + train pool");
        assert_eq!(led.balance(case["owner_f"].as_str().unwrap()),
                   d["owner_after"].as_u64().unwrap(), "data share + data pool");
        assert_eq!(led.fee_data_pool, d["fee_data_pool"].as_u64().unwrap());
        assert_eq!(led.fee_train_pool, d["fee_train_pool"].as_u64().unwrap());
        assert_eq!(led.root(), d["root"].as_str().unwrap(), "post-drain root");
    }
}

fn data_tx_from(kind: &str, t: &Value) -> sestrian_core::token::AccountTx {
    use sestrian_core::token::*;
    let sig = hex::decode(t["sig_hex"].as_str().unwrap()).unwrap();
    match kind {
        "submit" => AccountTx::DataSubmit(DataSubmitTx {
            owner_pub: t["owner_pub"].as_str().unwrap().into(),
            data_hash: t["data_hash"].as_str().unwrap().into(),
            size_bytes: t["size_bytes"].as_u64().unwrap(),
            media_type: t["media_type"].as_str().unwrap().into(),
            stake: t["stake"].as_u64().unwrap(),
            nonce: t["nonce"].as_u64().unwrap(),
            da_root: t["da_root"].as_str().unwrap_or("").into(),
            sig,
        }),
        "challenge" => AccountTx::DataChallenge(DataChallengeTx {
            challenger_pub: t["challenger_pub"].as_str().unwrap().into(),
            data_id: t["data_id"].as_str().unwrap().into(),
            stake: t["stake"].as_u64().unwrap(),
            reason: t["reason"].as_str().unwrap().into(),
            nonce: t["nonce"].as_u64().unwrap(), sig,
        }),
        _ => AccountTx::DataVote(DataVoteTx {
            voter_pub: t["voter_pub"].as_str().unwrap().into(),
            challenge_id: t["challenge_id"].as_str().unwrap().into(),
            support: t["support"].as_bool().unwrap(),
            nonce: t["nonce"].as_u64().unwrap(), sig,
        }),
    }
}

#[test]
fn data_lane_matches_reference() {
    use sestrian_core::token::{address, data_root, TokenLedger};
    use std::collections::HashSet;
    for case in vectors()["data_lane"].as_array().unwrap() {
        let mut led = TokenLedger::new();
        led.seed_genesis_data(&address(case["founder_pub"].as_str().unwrap()));
        assert_eq!(led.root(), case["root_genesis"].as_str().unwrap(),
                   "genesis registry serialization mismatch");
        let sub = data_tx_from("submit", &case["submit"]);
        assert_eq!(hex::encode(sub.signing_bytes()),
                   case["submit"]["signing_bytes_hex"].as_str().unwrap());
        assert_eq!(sub.txid(), case["submit"]["txid"].as_str().unwrap());
        // fund the submitter exactly as the reference did
        let owner = case["submit"]["owner_pub"].as_str().unwrap().to_string();
        led.apply_reward(1, &[owner.clone()], &owner, &[], &Default::default(), &Default::default());
        assert!(led.apply_data_tx(&sub, 1, &HashSet::new()));
        assert_eq!(led.root(), case["root_after_submit"].as_str().unwrap());
        let challenger = case["challenge"]["challenger_pub"].as_str().unwrap().to_string();
        led.apply_reward(2, &[challenger.clone()], &challenger, &[], &Default::default(), &Default::default());
        let ch = data_tx_from("challenge", &case["challenge"]);
        assert!(led.apply_data_tx(&ch, 2, &HashSet::new()));
        // CHALLENGE_QUORUM disinterested jurors vote to uphold
        let votes_json = case["votes"].as_array().unwrap();
        let votes: Vec<_> = votes_json.iter().map(|vj| data_tx_from("vote", vj)).collect();
        let jurors: HashSet<String> = votes.iter()
            .map(|v| v.sender_pub().to_string()).collect();
        for vote in &votes {
            assert!(led.apply_data_tx(vote, 3, &jurors), "quorum juror vote must apply");
        }
        assert_eq!(led.root(), case["root_after_vote"].as_str().unwrap());
        led.resolve_expired_challenges(case["resolve_height"].as_u64().unwrap());
        assert_eq!(led.root(), case["root_after_resolve"].as_str().unwrap(),
                   "challenge resolution mismatch");
        assert_eq!(led.balance(&sestrian_core::token::address(&challenger)),
                   case["challenger_balance_after"].as_u64().unwrap());
        let mut all = vec![sub, ch];
        all.extend(votes);
        assert_eq!(data_root(&all), case["data_root_of_all"].as_str().unwrap());
    }
}

fn spec_from(s: &Value) -> core::model_state::ModelSpec {
    core::model_state::ModelSpec {
        n_layers: s["n_layers"].as_u64().unwrap(),
        d_model: s["d_model"].as_u64().unwrap(),
        d_ff: s["d_ff"].as_u64().unwrap(),
        n_experts_initial: s["n_experts_initial"].as_u64().unwrap(),
        e_max: s["e_max"].as_u64().unwrap(),
        backbone_params: s["backbone_params"].as_u64().unwrap(),
    }
}

fn params_from(spec: core::model_state::ModelSpec, p: &Value) -> core::model_state::GenesisParams {
    core::model_state::GenesisParams {
        spec,
        retarget_window: p["retarget_window"].as_u64().unwrap(),
        target_deltas: p["target_deltas"].as_i64().unwrap(),
        quota_min_4dp: p["quota_min_4dp"].as_i64().unwrap(),
        quota_max_4dp: p["quota_max_4dp"].as_i64().unwrap(),
        stale_ceiling_4dp: p["stale_ceiling_4dp"].as_i64().unwrap(),
        k_sustain: p["k_sustain"].as_i64().unwrap(),
        growth_bound: p["growth_bound"].as_i64().unwrap(),
        announce_lead: p["announce_lead"].as_u64().unwrap(),
        delta_max_nnz: 1_000_000,
        v3_height: 1_000_000_000,
        v4_height: 1_000_000_000,
        growth_quorum: 3,
    }
}

fn pages_from(v: &Value) -> Vec<core::model_state::Page> {
    v.as_array().unwrap().iter().map(|p| {
        let a = p.as_array().unwrap();
        core::model_state::Page {
            start: a[0].as_u64().unwrap(),
            end: a[1].as_u64().unwrap(),
            kind: a[2].as_str().unwrap().into(),
            layer: a[3].as_i64().unwrap(),
            expert: a[4].as_i64().unwrap(),
            status: a[5].as_str().unwrap().into(),
        }
    }).collect()
}

#[test]
fn full_chain_replay_matches_reference() {
    // v1: a mini MoE chain with page-claimed deltas, eligibility attempts, a
    // fork, transfers, a data submit, window rollovers, AND an on-chain growth
    // activation with a post-growth block. Rust must rebuild every block,
    // validate it completely, run fork choice, and land on the same head with
    // the same roots — bit-exact ACROSS the dimension change.
    use sestrian_core::blocktree::{Block, BlockTree};
    use sestrian_core::model_state::{fold, page_init, page_state_root, ModelState};
    use std::collections::HashMap;
    for case in vectors()["chain_replay"].as_array().unwrap() {
        let spec = spec_from(&case["spec"]);
        let params = params_from(spec.clone(), &case["params"]);
        let genesis_w = i64s(&case["genesis_w"]);
        let mut tree = BlockTree::new(
            genesis_w.clone(),
            Some(case["data_contributor"].as_str().unwrap().into()),
            params.clone());
        for b in case["blocks"].as_array().unwrap() {
            let header = header_from(&b["header"]);
            assert_eq!(header.block_hash(), b["hash"].as_str().unwrap(),
                       "header serialization drift");
            let txs: Vec<core::BackpropTx> =
                b["txs"].as_array().unwrap().iter().map(tx_from).collect();
            let bodies: HashMap<String, Vec<i64>> = b["bodies"].as_object().unwrap()
                .iter().map(|(k, v)| (k.clone(), i64s(v))).collect();
            let transfers = b["transfers"].as_array().unwrap()
                .iter().map(transfer_from).collect();
            let data_txs = b["data_txs"].as_array().unwrap()
                .iter().map(|t| data_tx_from("submit", t)).collect();
            // full first-principles validation: sigs, DA hashes, page claims,
            // quota, eligibility, per-page transition + growth activation,
            // txset/score/sketch/transfer/data/ledger roots — then fork choice
            let scores: std::collections::BTreeMap<String, u64> =
                b.get("scores").and_then(|v| v.as_object())
                    .map(|m| m.iter()
                        .filter_map(|(k, x)| x.as_u64().map(|s| (k.clone(), s)))
                        .collect())
                    .unwrap_or_default();
            let sketches: std::collections::BTreeMap<String, Vec<i32>> =
                b.get("sketches").and_then(|v| v.as_object())
                    .map(|m| m.iter()
                        .filter_map(|(k, x)| x.as_array().map(|a| (
                            k.clone(),
                            a.iter().map(|e| e.as_i64().unwrap_or(0) as i32).collect(),
                        )))
                        .collect())
                    .unwrap_or_default();
            tree.add_block(Block { header, txs, bodies, sparse: HashMap::new(), transfers, data_txs, scores,
                                   sketches })
                .expect("reference block must validate");
        }
        assert_eq!(tree.head, case["expected_head"].as_str().unwrap(),
                   "fork choice disagrees with reference");
        // THE RESTART-WEDGE INVARIANT, checked on a real forked chain.
        // Fast-boot cannot adopt a rival of its own snapshot block: connecting
        // that rival needs the PARENT state, which lies below the checkpoint.
        // So a snapshot taken AT the head puts the state floor exactly where a
        // live proposal tie can exist, and a node restarted onto the losing
        // side of one can never rejoin — how the EU anchor (tie at 252) and
        // then the US anchor (tie at 276) each wedged for hours. Checkpointing
        // the head's PARENT keeps every head tie above the floor.
        let head_h = tree.blocks[&tree.head].height;
        if head_h >= 2 {
            let (basis, basis_state) = tree.snapshot_basis();
            assert_ne!(basis, tree.head,
                       "snapshot must NOT checkpoint the head — that is the \
                        restart-wedge that stranded two anchors");
            assert_eq!(basis, tree.blocks[&tree.head].prev_hash,
                       "snapshot must checkpoint the head's parent");
            assert_eq!(basis_state.len(), tree.head_state().len(),
                       "checkpoint state must be a usable full weight vector");
        }
        assert_eq!(page_state_root(tree.head_state(), tree.head_model()),
                   case["expected_state_root"].as_str().unwrap());
        assert_eq!(tree.head_model().model_root(),
                   case["expected_model_root"].as_str().unwrap());
        assert_eq!(tree.head_model().dim(), case["expected_dim"].as_u64().unwrap(),
                   "growth must have extended the state");
        assert_eq!(tree.head_model().pages.len(),
                   case["expected_n_pages"].as_u64().unwrap() as usize);
        assert_eq!(tree.head_ledger().root(),
                   case["expected_ledger_root"].as_str().unwrap());
        assert_eq!(tree.head_ledger().supply(),
                   case["expected_supply"].as_u64().unwrap());
        assert_eq!(tree.blocks[&tree.head].height,
                   case["expected_head_height"].as_u64().unwrap());

        // Independent full replay from genesis (§3.5): re-apply every head-chain
        // block's per-page transitions AND the ModelState fold, including the
        // growth activation (page append) — bit-exact across the dim change.
        let by_hash: HashMap<&str, &Value> = case["blocks"].as_array().unwrap()
            .iter().map(|b| (b["hash"].as_str().unwrap(), b)).collect();
        let mut chain: Vec<&Value> = Vec::new();
        let mut cur = case["expected_head"].as_str().unwrap();
        while cur != tree.genesis_hash {
            let b = by_hash[cur];
            chain.push(b);
            cur = b["parent"].as_str().unwrap();
        }
        chain.reverse();
        let mut w = genesis_w.clone();
        let mut model = ModelState::genesis(&params.spec);
        for b in chain {
            let txs: Vec<core::BackpropTx> =
                b["txs"].as_array().unwrap().iter().map(tx_from).collect();
            let bodies: Vec<Vec<i64>> = txs.iter()
                .map(|t| i64s(&b["bodies"][&t.da_pointer])).collect();
            let claims: Vec<Vec<u32>> = txs.iter().map(|t| t.canonical_pages()).collect();
            let spans: Vec<(u64, u64)> =
                model.pages.iter().map(|p| (p.start, p.end)).collect();
            w = core::paged_transition(&w, &bodies, &claims, &spans);
            let zero_scored = txs.iter()
                .filter(|t| b["scores"][&t.txid()].as_u64().unwrap_or(0) == 0)
                .count() as u64;
            let h = &b["header"];
            let score_sum: u64 = txs.iter()
                .map(|t| b["scores"][&t.txid()].as_u64().unwrap_or(0)).sum();
            let (next, activations) = fold(&model, &params,
                                           h["height"].as_u64().unwrap(),
                                           txs.len() as u64, zero_scored,
                                           h["prev_hash"].as_str().unwrap(),
                                           score_sum,
                                           h["proposer"].as_str().unwrap_or(""));
            model = next;
            for (page_id, _l, _e, trigger) in &activations {
                w.extend(page_init(trigger, *page_id, &params.spec));
            }
        }
        assert_eq!(page_state_root(&w, &model),
                   case["replay_state_root"].as_str().unwrap(),
                   "replay from genesis must be bit-exact across the dim change");
    }
}

#[test]
fn page_root_matches_reference() {
    // v1 state commitment: domain-separated page-Merkle root over page bytes
    // (0x00 leaf / 0x01 node, odd node promoted by hashing with itself).
    use sestrian_core::model_state::{page_state_root, ModelState};
    for case in vectors()["page_root"].as_array().unwrap() {
        let w = i64s(&case["w"]);
        let pages = pages_from(&case["pages"]);
        if let Some(leaf0) = case.get("leaf0_hex").and_then(|x| x.as_str()) {
            let p0 = &pages[0];
            let bytes = core::int64_bytes(&w[p0.start as usize..p0.end as usize]);
            assert_eq!(hex::encode(core::merkle::leaf_hash(&bytes)), leaf0,
                       "leaf hash (0x00 domain separation)");
        }
        let st = ModelState {
            pages,
            quota_4dp: 10_000,
            pinned_streak: 0,
            slack_streak: 0,
            pending_growth: vec![],
            window_id: 0,
            win_accepted: 0,
            win_zero_scored: 0,
            win_score_sum: 0,
            rev: 2,
            win_scorers: vec![],
            events_total: 0,
        };
        assert_eq!(page_state_root(&w, &st), case["root"].as_str().unwrap(),
                   "page-Merkle root mismatch");
    }
}

#[test]
fn page_init_matches_reference() {
    // v1 deterministic new-expert init: the SHA-256 hash-stream, byte-exact
    // (big-endian u64 lanes; weight coords ±0.02 fixed point; biases zero).
    use sestrian_core::model_state::{page_init, ModelSpec};
    for case in vectors()["page_init"].as_array().unwrap() {
        let spec = ModelSpec {
            n_layers: 1,
            d_model: case["d_model"].as_u64().unwrap(),
            d_ff: case["d_ff"].as_u64().unwrap(),
            n_experts_initial: 1, e_max: 2, backbone_params: 0,
        };
        assert_eq!(spec.expert_page_len(), case["page_len"].as_u64().unwrap());
        let init = page_init(case["trigger"].as_str().unwrap(),
                             case["page_id"].as_u64().unwrap(), &spec);
        assert_eq!(init, i64s(&case["init"]), "page_init hash-stream mismatch");
    }
}

#[test]
fn model_state_matches_reference() {
    // v1 ModelState commitment: canonical JSON must byte-match Python's
    // json.dumps(sort_keys=True, separators=(",",":")); model_root = sha256 of
    // it. Round-trip through the parsed form pins field handling.
    use sestrian_core::model_state::ModelState;
    for case in vectors()["model_state"].as_array().unwrap() {
        let want_json = case["canonical_json"].as_str().unwrap();
        let parsed: Value = serde_json::from_str(want_json).unwrap();
        let st = ModelState::from_json_value(&parsed)
            .expect("canonical JSON must parse into a ModelState");
        assert_eq!(st.canonical_json(), want_json,
                   "canonical JSON serialization drift");
        assert_eq!(st.model_root(), case["root"].as_str().unwrap());
    }
}

#[test]
fn quota_matches_reference() {
    // v1 work quota: required_nnz = claimed_params * quota_4dp // 1_000_000
    // (floor, i128 intermediates). The spec is the controller_fold spec.
    use sestrian_core::model_state::ModelState;
    let v = vectors();
    let spec = spec_from(&v["controller_fold"][0]["spec"]);
    for case in v["quota"].as_array().unwrap() {
        let mut st = ModelState::genesis(&spec);
        assert_eq!(st.dim(), case["spec_dim"].as_u64().unwrap(),
                   "quota family spec must match the controller_fold spec");
        assert_eq!(spec.expert_page_len(),
                   case["expert_page_len"].as_u64().unwrap());
        let all: Vec<u32> = (0..st.pages.len() as u32).collect();
        for row in case["rows"].as_array().unwrap() {
            st.quota_4dp = row["quota_4dp"].as_i64().unwrap();
            assert_eq!(st.required_nnz(&all), row["all_pages"].as_u64().unwrap());
            assert_eq!(st.required_nnz(&[1]), row["one_expert"].as_u64().unwrap());
            assert_eq!(st.required_nnz(&[0]), row["backbone"].as_u64().unwrap());
        }
        // v2 ENVELOPE: budget = delta_max_nnz * 1e6 / quota_4dp (floor) — the
        // claimable-params bound that turns capacity pressure into
        // specialization instead of bigger payloads
        for row in case["envelope"].as_array().unwrap() {
            let cap = row["delta_max_nnz"].as_u64().unwrap() as u128;
            let q = row["quota_4dp"].as_u64().unwrap() as u128;
            let budget = cap * 1_000_000 / q;
            assert_eq!(budget as u64,
                       row["claim_budget_params"].as_u64().unwrap());
        }
    }
}

#[test]
fn controller_fold_matches_reference() {
    // v1 consensus fold: scripted per-block signals -> per-step model_root,
    // activations (page appends), final dim + root. This pins the entire
    // window machinery: retarget, schedule, activation, freeze, thaw.
    use sestrian_core::model_state::{fold, ModelState};
    for case in vectors()["controller_fold"].as_array().unwrap() {
        let spec = spec_from(&case["spec"]);
        let params = params_from(spec.clone(), &case["params"]);
        let mut st = ModelState::genesis(&spec);
        for step in case["steps"].as_array().unwrap() {
            let (next, activations) = fold(
                &st, &params,
                step["height"].as_u64().unwrap(),
                step["n_txs"].as_u64().unwrap(),
                step["zero_scored"].as_u64().unwrap(),
                step["prev_hash"].as_str().unwrap(), 0, "");
            st = next;
            let want_acts: Vec<Value> = step["activations"].as_array().unwrap().clone();
            assert_eq!(activations.len(), want_acts.len(),
                       "activation count @h{}", step["height"]);
            for (got, want) in activations.iter().zip(&want_acts) {
                let a = want.as_array().unwrap();
                assert_eq!(got.0, a[0].as_u64().unwrap(), "activated page id");
                assert_eq!(got.1, a[1].as_i64().unwrap(), "activated layer");
                assert_eq!(got.2, a[2].as_i64().unwrap(), "activated expert idx");
                assert_eq!(got.3, a[3].as_str().unwrap(), "activation trigger");
            }
            assert_eq!(st.model_root(), step["model_root"].as_str().unwrap(),
                       "model_root diverged at height {}", step["height"]);
        }
        assert_eq!(st.dim(), case["final_dim"].as_u64().unwrap());
        assert_eq!(st.model_root(), case["final_model_root"].as_str().unwrap());
    }
}

#[test]
fn da_matches_reference() {
    use sestrian_core::da;
    use std::collections::BTreeMap;
    for case in vectors()["da"].as_array().unwrap() {
        let body = hex::decode(case["body_hex"].as_str().unwrap()).unwrap();
        let k = case["k"].as_u64().unwrap() as usize;
        let n = case["n"].as_u64().unwrap() as usize;

        // erasure shards reproduce byte-for-byte
        let shards = da::encode(&body, k, n);
        let want: Vec<Vec<u8>> = case["shards_hex"].as_array().unwrap().iter()
            .map(|s| hex::decode(s.as_str().unwrap()).unwrap()).collect();
        assert_eq!(shards, want, "erasure shards must match the reference");

        // Merkle root matches
        let blob = da::disperse(&body, k, n);
        assert_eq!(hex::encode(blob.root()), case["root_hex"].as_str().unwrap());

        // reconstruct from the reference's k-subset equals the body
        let keep: Vec<usize> = case["reconstruct_from"].as_array().unwrap().iter()
            .map(|x| x.as_u64().unwrap() as usize).collect();
        let mut sub = BTreeMap::new();
        for i in keep { sub.insert(i, blob.shards[i].clone()); }
        let recon = da::reconstruct(&sub, k, blob.orig_len).unwrap();
        assert_eq!(recon, body, "reconstruct from k shards must equal the body");

        // Merkle proof reproduces, verifies, and rejects a forged shard
        let pi = case["proof_index"].as_u64().unwrap() as usize;
        let proof = blob.proof(pi);
        let want_proof = case["proof"].as_array().unwrap();
        assert_eq!(proof.len(), want_proof.len(), "proof length");
        for (got, wp) in proof.iter().zip(want_proof) {
            let side = wp[0].as_str().unwrap().chars().next().unwrap();
            assert_eq!(got.0, side, "proof side");
            assert_eq!(hex::encode(got.1), wp[1].as_str().unwrap(), "proof sibling");
        }
        assert!(da::merkle_verify(&blob.shards[pi], &proof, &blob.root()));
        let forged = vec![0u8; blob.shards[pi].len()];
        assert!(!da::merkle_verify(&forged, &proof, &blob.root()),
                "a forged shard must fail its Merkle proof");
    }
}

#[test]
fn capacity_retarget_matches_reference() {
    // v1: the INTEGER controller — every window event, including the derived
    // accepted/staleness signals inside simulate, must reproduce exactly.
    use sestrian_core::capacity::{simulate, CapacityRetarget};
    for case in vectors()["capacity"].as_array().unwrap() {
        let fleet: Vec<i64> = i64s(&case["fleet_2dp"]);
        let per_unit = case["per_unit"].as_i64().unwrap();
        let mut ctrl = CapacityRetarget::default();
        let events = simulate(&mut ctrl, &fleet, per_unit);
        let windows = case["windows"].as_array().unwrap();
        assert_eq!(events.len(), windows.len());
        for (d, w) in events.iter().zip(windows) {
            assert_eq!(d.window, w["window"].as_u64().unwrap());
            assert_eq!(d.grew, w["grew"].as_i64().unwrap(), "grew @w{}", d.window);
            assert_eq!(d.froze, w["froze"].as_i64().unwrap(), "froze @w{}", d.window);
            assert_eq!(d.thawed, w["thawed"].as_i64().unwrap(), "thawed @w{}", d.window);
            assert_eq!(d.scheduled, w["scheduled"].as_i64().unwrap(),
                       "scheduled @w{}", d.window);
            assert_eq!(d.quota_4dp, w["quota_4dp"].as_i64().unwrap(),
                       "quota_4dp @w{}", d.window);
            assert_eq!(d.total, w["total"].as_i64().unwrap(), "total @w{}", d.window);
            assert_eq!(d.active, w["active"].as_i64().unwrap(), "active @w{}", d.window);
        }
    }
}

#[test]
fn lottery_matches_reference() {
    // v1: attempt-widened sortition — cases cover a whale, dust, a widened
    // attempt, zero stake, the cold start, and the ATTEMPT_MAX liveness floor.
    use sestrian_core::{lottery, Key};
    for case in vectors()["lottery"].as_array().unwrap() {
        let pub_hex = case["pub"].as_str().unwrap();
        let prev = case["prev_hash"].as_str().unwrap();
        let h = case["height"].as_u64().unwrap();
        let attempt = case["attempt"].as_u64().unwrap();
        // reprove the VRF from the secret: Rust must produce the same proof
        let seed: [u8; 32] = hex::decode(case["seed_hex"].as_str().unwrap())
            .unwrap().try_into().unwrap();
        let key = Key::from_seed(seed);
        let proof = lottery::vrf_prove(&key, prev, h, attempt);
        assert_eq!(hex::encode(&proof), case["proof_sig_hex"].as_str().unwrap(),
                   "VRF proof (deterministic Ed25519) must match");
        assert_eq!(hex::encode(lottery::vrf_output(&proof)),
                   case["vrf_output_hex"].as_str().unwrap(), "VRF output");
        assert_eq!(lottery::attempt_work(&proof, attempt),
                   case["work"].as_u64().unwrap(),
                   "attempt-discounted work @attempt {attempt}");
        let stake = case["stake"].as_u64().unwrap();
        let total = case["total_stake"].as_u64().unwrap();
        assert_eq!(lottery::eligible(pub_hex, &proof, prev, h, attempt, stake, total),
                   case["eligible"].as_bool().unwrap(),
                   "eligibility (stake {stake}/{total}, attempt {attempt})");
        // a forged proof (wrong signer) is never eligible, even at ATTEMPT_MAX
        assert!(!lottery::eligible("00".repeat(32).as_str(), &proof, prev, h,
                                   attempt, stake, total),
                "eligibility must reject a proof that doesn't verify");
    }
}

#[test]
fn bond_lifecycle_matches_reference() {
    use sestrian_core::token::{address, TokenLedger, BOND_WINDOW};
    for case in vectors()["bond"].as_array().unwrap() {
        let miner = case["miner"].as_str().unwrap();
        let addr = address(miner);
        let mut led = TokenLedger::new();
        led.apply_reward(1, &[miner.to_string()], miner, &[], &Default::default(), &Default::default());
        assert_eq!(led.balance(&addr), case["bal_after_reward"].as_u64().unwrap());
        let bond = case["bond"].as_u64().unwrap();
        assert!(led.lock_bond("delta-tx-1", &addr, bond, 1), "bond must lock");
        assert_eq!(led.root(), case["root_locked"].as_str().unwrap(), "root after lock");
        assert_eq!(led.balance(&addr), case["bal_locked"].as_u64().unwrap());
        led.resolve_expired_bonds(1 + BOND_WINDOW);
        assert_eq!(led.root(), case["root_returned"].as_str().unwrap(), "root after return");
        assert_eq!(led.balance(&addr), case["bal_returned"].as_u64().unwrap());
        // insufficient balance is rejected (no state change)
        let over = led.balance(&addr) + 1;
        assert!(!led.lock_bond("delta-tx-2", &addr, over, 100),
                "a bond the miner can't afford is rejected");
    }
}

#[test]
fn inference_receipt_matches_reference() {
    use sestrian_core::token::{address, AccountTx, InferenceReceiptTx, TokenLedger};
    use std::collections::HashSet;
    for case in vectors()["inference"].as_array().unwrap() {
        let payer = case["payer_pub"].as_str().unwrap();
        let rcpt = AccountTx::InferenceReceipt(InferenceReceiptTx {
            payer_pub: payer.into(),
            server_addr: case["server_addr"].as_str().unwrap().into(),
            fee: case["fee"].as_u64().unwrap(),
            output_hash: case["output_hash"].as_str().unwrap().into(),
            head_root: case["head_root"].as_str().unwrap().into(),
            nonce: case["nonce"].as_u64().unwrap(),
            answer_sketch: vec![],
            sig: hex::decode(case["sig_hex"].as_str().unwrap()).unwrap(),
        });
        assert_eq!(hex::encode(rcpt.signing_bytes()),
                   case["signing_bytes_hex"].as_str().unwrap());
        assert_eq!(rcpt.txid(), case["txid"].as_str().unwrap());
        let mut led = TokenLedger::new();
        led.apply_reward(1, &[payer.to_string()], payer, &[], &Default::default(), &Default::default());
        assert!(led.apply_data_tx(&rcpt, 5, &HashSet::new()), "receipt must apply");
        assert_eq!(led.balance(&address(payer)), case["payer_after"].as_u64().unwrap());
        assert_eq!(led.balance(case["server_addr"].as_str().unwrap()),
                   case["server_after"].as_u64().unwrap());
        assert_eq!(led.root(), case["root_after"].as_str().unwrap());
    }
}

#[test]
fn sketches_match_reference() {
    // rev 8: sketch_root canonical form, the alignment-split receipt (aligned ->
    // owner paid directly, anti-aligned -> pooled), signing-bytes parity for
    // the answer_sketch framed field. Delta-sketch VALUES are committed data
    // (the hash projection lives in the rig only), so the vector supplies them.
    use sestrian_core::blocktree::{sketch_root, SKETCH_DIM};
    use sestrian_core::token::{AccountTx, InferenceReceiptTx, TokenLedger};
    use std::collections::{BTreeMap, HashSet};
    for case in vectors()["sketches"].as_array().unwrap() {
        let sk: Vec<i32> = case["sketch"].as_array().unwrap()
            .iter().map(|x| x.as_i64().unwrap() as i32).collect();
        assert_eq!(sk.len(), SKETCH_DIM);
        let m: BTreeMap<String, Vec<i32>> = [("tx0".to_string(), sk)].into();
        assert_eq!(sketch_root(&m), case["sketch_root"].as_str().unwrap(),
                   "sketch_root canonical JSON drift");
        let dim = case["dim"].as_u64().unwrap() as usize;
        let owner = case["owner"].as_str().unwrap();
        let payer = case["payer"].as_str().unwrap();
        let mut led = TokenLedger::new();
        led.registry.insert("corpusS".into(), serde_json::json!({
            "owner": owner, "data_hash": "corpusS", "size": 0,
            "media_type": "text", "stake": 0, "weight": 1, "status": "active",
            "sketch": vec![case["corpus_sketch_entry"].as_i64().unwrap(); dim]}));
        led.apply_reward(1, &[payer.to_string()], "genesis", &[],
                         &Default::default(), &Default::default());
        let mk = |nonce: u64, entry: i64, sig_hex: &str| {
            AccountTx::InferenceReceipt(InferenceReceiptTx {
                payer_pub: payer.into(),
                server_addr: case["server"].as_str().unwrap().into(),
                fee: case["fee"].as_u64().unwrap(),
                output_hash: "aa".repeat(32), head_root: "bb".repeat(32),
                nonce,
                answer_sketch: vec![entry; dim],
                sig: hex::decode(sig_hex).unwrap(),
            })
        };
        let a = &case["aligned"];
        let pos = mk(0, a["answer_entry"].as_i64().unwrap(),
                     a["sig_hex"].as_str().unwrap());
        if let AccountTx::InferenceReceipt(t) = &pos {
            assert_eq!(hex::encode(t.signing_bytes()),
                       a["signing_bytes_hex"].as_str().unwrap(),
                       "answer_sketch framed-field drift");
        }
        assert!(led.apply_data_tx(&pos, 2, &HashSet::new()));
        assert_eq!(led.balance(owner), a["owner_after"].as_u64().unwrap(),
                   "aligned answer must pay the owner directly");
        assert_eq!(led.fee_data_pool, a["fee_data_pool_after"].as_u64().unwrap());
        assert_eq!(led.root(), a["root_after"].as_str().unwrap());
        let n = &case["anti"];
        let neg = mk(1, n["answer_entry"].as_i64().unwrap(),
                     n["sig_hex"].as_str().unwrap());
        if let AccountTx::InferenceReceipt(t) = &neg {
            assert_eq!(hex::encode(t.signing_bytes()),
                       n["signing_bytes_hex"].as_str().unwrap());
        }
        assert!(led.apply_data_tx(&neg, 3, &HashSet::new()));
        assert_eq!(led.balance(owner), n["owner_after"].as_u64().unwrap(),
                   "anti-aligned answer must NOT pay the owner");
        assert_eq!(led.fee_data_pool, n["fee_data_pool_after"].as_u64().unwrap());
        assert_eq!(led.root(), n["root_after"].as_str().unwrap());
    }
}


#[test]
fn v4_fold_matches_reference() {
    // v4: the QUORUM gate. Pins the activation boundary (win_scorers enters
    // the canonical JSON exactly at v4_height), proposer dedupe, the quorum
    // cap, the anonymous-proposer rule, the window reset, and both gate
    // outcomes to the Python reference — the whole rule, byte for byte.
    use sestrian_core::model_state::{fold, GenesisParams, ModelState};
    let v = vectors();
    let case = &v["v4_fold"][0];
    let spec = spec_from(&v["controller_fold"][0]["spec"]);
    let mut params = GenesisParams::new(spec);
    params.retarget_window = case["retarget_window"].as_u64().unwrap();
    params.target_deltas = case["target_deltas"].as_i64().unwrap();
    params.quota_max_4dp = case["quota_max_4dp"].as_i64().unwrap();
    params.k_sustain = case["k_sustain"].as_i64().unwrap();
    params.announce_lead = case["announce_lead"].as_u64().unwrap();
    params.v3_height = case["v3_height"].as_u64().unwrap();
    params.v4_height = case["v4_height"].as_u64().unwrap();
    params.growth_quorum = case["growth_quorum"].as_u64().unwrap() as usize;
    let mut st = ModelState::genesis(&params.spec);
    for step in case["steps"].as_array().unwrap() {
        let (next, acts) = fold(&st, &params,
                                step["height"].as_u64().unwrap(),
                                step["n_txs"].as_u64().unwrap(),
                                step["zero_scored"].as_u64().unwrap(),
                                step["prev_hash"].as_str().unwrap(),
                                step["score_sum"].as_u64().unwrap(),
                                step["proposer"].as_str().unwrap());
        st = next;
        assert_eq!(st.rev, step["rev"].as_u64().unwrap(),
                   "v4 rev diverged at h{}", step["height"]);
        let want: Vec<String> = step["win_scorers"].as_array().unwrap().iter()
            .map(|x| x.as_str().unwrap().to_string()).collect();
        assert_eq!(st.win_scorers, want,
                   "v4 scorer set diverged at h{}", step["height"]);
        assert_eq!(st.model_root(), step["model_root"].as_str().unwrap(),
                   "v4 fold diverged at h{}", step["height"]);
        assert_eq!(acts.len(), step["activations"].as_array().unwrap().len());
    }
    assert_eq!(st.events_total, case["final_events"].as_u64().unwrap());
    assert_eq!(st.pending_growth.len(),
               case["final_pending"].as_array().unwrap().len());
}

#[test]
fn v3_fold_matches_reference() {
    // v3: the scheduled-upgrade boundary (rev + win_score_sum enter the
    // canonical JSON exactly at v3_height) and the LEARNING GATE (growth
    // requires the window's summed committed scores > 0). Pins the entire
    // activation sequence to the Python reference.
    use sestrian_core::model_state::{fold, GenesisParams, ModelState};
    let v = vectors();
    let case = &v["v3_fold"][0];
    let spec = spec_from(&v["controller_fold"][0]["spec"]);
    let mut params = GenesisParams::new(spec);
    params.retarget_window = case["retarget_window"].as_u64().unwrap();
    params.target_deltas = case["target_deltas"].as_i64().unwrap();
    params.quota_max_4dp = case["quota_max_4dp"].as_i64().unwrap();
    params.k_sustain = case["k_sustain"].as_i64().unwrap();
    params.announce_lead = case["announce_lead"].as_u64().unwrap();
    params.v3_height = case["v3_height"].as_u64().unwrap();
    let mut st = ModelState::genesis(&params.spec);
    for step in case["steps"].as_array().unwrap() {
        let (next, acts) = fold(&st, &params,
                                step["height"].as_u64().unwrap(),
                                step["n_txs"].as_u64().unwrap(),
                                step["zero_scored"].as_u64().unwrap(),
                                step["prev_hash"].as_str().unwrap(),
                                step["score_sum"].as_u64().unwrap(), "");
        st = next;
        assert_eq!(st.rev, step["rev"].as_u64().unwrap());
        assert_eq!(st.model_root(), step["model_root"].as_str().unwrap(),
                   "v3 fold diverged at h{}", step["height"]);
        assert_eq!(acts.len(),
                   step["activations"].as_array().unwrap().len());
    }
    assert_eq!(st.events_total, case["final_events"].as_u64().unwrap());
    assert_eq!(st.pending_growth.len(),
               case["final_pending"].as_array().unwrap().len());
}

/// §7.2a corpus availability: the chunking and the two-level Merkle
/// construction, pinned to the Python reference. A port that chunked at a
/// different size, ordered chunk roots differently, or hashed the manifest
/// another way would still emit a 64-hex string — and would silently accept
/// corpora the reference rejects, which is the failure this vector exists to
/// catch. Spans a partial tail chunk in both directions.
#[test]
fn corpus_da_matches_reference() {
    use core::corpus;
    let v = vectors();
    let f = &v["corpus_da"][0];

    assert_eq!(f["chunk_bytes"].as_u64().unwrap(), corpus::CHUNK_BYTES as u64,
               "CHUNK_BYTES is consensus-critical: it determines every da_root");
    assert_eq!(f["chunk_k"].as_u64().unwrap(), corpus::CHUNK_K as u64);
    assert_eq!(f["chunk_n"].as_u64().unwrap(), corpus::CHUNK_N as u64);

    for case in f["cases"].as_array().unwrap() {
        let n = case["size_bytes"].as_u64().unwrap() as usize;
        // rebuild the exact body the generator used
        let pattern = b"sestrian-corpus-vector|";
        let mut body = Vec::with_capacity(n);
        while body.len() < n {
            body.extend_from_slice(pattern);
        }
        body.truncate(n);

        let m = corpus::build(&body[..]).unwrap();
        assert_eq!(m.data_hash, case["body_sha256"].as_str().unwrap(),
                   "corpus sha256 diverged at size {n}");
        assert_eq!(corpus::chunk_count(n as u64),
                   case["expected_chunks"].as_u64().unwrap(),
                   "chunk count diverged at size {n}");
        let want_roots: Vec<String> = case["chunk_roots_hex"].as_array().unwrap()
            .iter().map(|r| r.as_str().unwrap().to_string()).collect();
        let got_roots: Vec<String> = m.chunk_roots.iter().map(hex::encode).collect();
        assert_eq!(got_roots, want_roots, "chunk roots diverged at size {n}");
        assert_eq!(m.da_root, case["expected_da_root"].as_str().unwrap(),
                   "da_root diverged at size {n}");
    }
}
